### ISSUE TITLE
Implement save code feature

### ISSUE THREAD

**Issue by sahildua2305** [sahildua2305/hackIDE#13]

**Comment by sahildua2305** [comment]
@prankymat Have you ever used mongodb with Django on Heroku?

**Comment by prankymat** [comment]
Not with django but I think this will help :)

http://django-mongodb-engine.readthedocs.org/en/latest/tutorial.html

**Comment by sahildua2305** [comment]
The problem isn't using mongoDB with Django. It's the deployment that's an issue. Heroku doesn't support adding mongoDB without adding a credit card in account.

**Comment by mananpal1997** [comment]
Why not use PostgreSQL?

**Comment by sahildua2305** [comment]
Exactly, why not?
No issues with using PostgreSQL, @mananpal1997. In fact I have been thinking about using it and provide the mentioned feature. Unable to find time recently. Are you up for this?

**Comment by mananpal1997** [comment]
I'll give it a try. :)

**Comment by Mechasparrow** [comment]
Wouldn't this be easier if you used something like pastebin?

**Comment by ardzoht** [comment]
Hi! I can help you with this

**Comment by sahildua2305** [comment]
@ardzoht Thanks for offering help! :blue_heart: 

However, there is already a PR for this issue #30

**Comment by sahildua2305** [comment]
Closed via #30
