### ISSUE TITLE
Boilerplate when hackIDE launches

### ISSUE THREAD

**Issue by prankymat** [sahildua2305/hackIDE#14]
Include a boilerplate template in the code editor when hackIDE launches. For example in C++:

```c++
#include <iostream>

int main() {
    // Enter your code here
    return 0;
}
```

This will greatly ease the use for users who just want to short codes quickly.

**Comment by rhnvrm** [comment]
I'm working on this. Will update soon.

**Comment by sahildua2305** [comment]
Ok @rhnvrm I'm marking it wip (work in progress). Looking forward to your contribution :)

**Comment by rhnvrm** [comment]
:+1:

**Comment by prankymat** [comment]
:+1:

**Comment by prankymat** [comment]
Big :+1: for adding this feature! However it seemed that this feature is not showing up live on heroku even it's merged to master. @sahildua2305

**Comment by sahildua2305** [comment]
It's live now. Had a couple of bugs. Removed them. @prankymat

**Comment by rhnvrm** [comment]
:+1:
