### ISSUE TITLE
Improve boiler template for Java

### ISSUE THREAD

**Issue by prankymat** [sahildua2305/hackIDE#17]
Instead of just saying ```//begin writing below``` it's better to include a boiler template just like other langs.

```java
public class TestDriver {
    public static void main(String[] args) {
        // Your code goes here
    }
}
```

will be a good one :)

**Comment by sahildua2305** [comment]
Can you create a PR? It's already available for most of the languages already. @prankymat

**Comment by prankymat** [comment]
@sahildua2305 Yes i'm working on it now :) I'm having trouble starting the server, what command should I use to run the server again?

**Comment by prankymat** [comment]
@sahildua2305 I've fixed the problem by using this:

``` HACKIDE_DEBUG=true python manage.py runserver ```

Will include this in the readme later in a PR.
