### ISSUE TITLE
Hi, i'm interested of your code. But it isn't work

### ISSUE THREAD

**Issue by hsyoon702** [sahildua2305/hackIDE#20]
But it isn't work your http://hackide.herokuapp.com/ site.

Compile and Run isn't work.

Please tell why this happen occured, and give me answer.

Thank ypu!

**Comment by prankymat** [comment]
@hsyoon702 thanks for your report. I've just ran a test on the live site. Here is my result.
![image](https://cloud.githubusercontent.com/assets/2998111/15309256/1e88b808-1b9a-11e6-8395-d035e0691381.png)

**Comment by hsyoon702** [comment]
What is the problem? I want to use this program so much!
Can you FIix it? Thanks.

**Comment by hsyoon702** [comment]
And I've downloaded this project, It isn't work either.
help me ㅠ.ㅠ

**Comment by prankymat** [comment]
It's more likely to be a server side error @sahildua2305 would you mind to have a look?

**Comment by sahildua2305** [comment]
Hi @hsyoon702

There is some problem with the HackerEarth API which is being used on the
backend of HackIDE. I have informed their CTO about this issue. Hoping to
get it resolved soon. You should be able to use it in a while.

Sorry fort he inconvenience.

On Tuesday 17 May 2016, hsyoon702 <notifications@github.com> wrote:

> What is the problem? I want to use this program so much!
> Can you FIix it? Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sahildua2305/hackIDE/issues/20#issuecomment-219601860>
>


-- 
Regards
*Sahil Dua*
Netaji Subhas Institute of Technology, New Delhi
Connect on LinkedIn <http://in.linkedin.com/in/sahildua2305>
*www.sahildua.com <http://www.sahildua.com>*

**Comment by hsyoon702** [comment]
Thanks to infrom me @sahildua2305, @prankymat .

I hope it recover soon.
If their CTO send mail to you, would you tell me in this issue board?

Thnak you!

**Comment by sahildua2305** [comment]
Yes, I'll definitely do that.

On Tuesday 17 May 2016, hsyoon702 <notifications@github.com> wrote:

> Thanks to infrom me @sahildua2305 <https://github.com/sahildua2305>,
> @prankymat <https://github.com/prankymat> .
>
> I hope it recover soon.
> If their CTO send mail to you, would you tell me in this issue board?
>
> Thnak you!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sahildua2305/hackIDE/issues/20#issuecomment-219603563>
>


-- 
Regards
*Sahil Dua*
Netaji Subhas Institute of Technology, New Delhi
Connect on LinkedIn <http://in.linkedin.com/in/sahildua2305>
*www.sahildua.com <http://www.sahildua.com>*

**Comment by sreeram-boyapati** [comment]
Hey, I work at HackerEarth. We got the issue fixed. It will not repeat again. Nice project btw :)

**Comment by hsyoon702** [comment]
Thanks it works! 
Thank you all of you!

**Comment by sahildua2305** [comment]
Thanks @sreeram-boyapati :)
