### ISSUE TITLE
Download code as a .zip file

### ISSUE THREAD

**Issue by sahildua2305** [sahildua2305/hackIDE#24]
Use some library like JSzip to convert the code file into a .zip one and then start download.

**Comment by mananpal1997** [comment]
Please see the pull request regarding it. :)

**Comment by sahildua2305** [comment]
@mananpal1997 Did you update your PR?

**Comment by mananpal1997** [comment]
@sahildua2305 No, I haven't made much changes since the last pull.

**Comment by sahildua2305** [comment]
Do you need help in completing this? Are you still interested?

On Tuesday 14 June 2016, Manan Pal Singh <notifications@github.com> wrote:

> @sahildua2305 <https://github.com/sahildua2305> No, I haven't made much
> changes since the last pull.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sahildua2305/hackIDE/issues/24#issuecomment-225780022>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE9xBWBjM9vTWSjqugGMfijUI2JckIDZks5qLjSygaJpZM4IvCB9>
> .
>


-- 
Regards
*Sahil Dua*
Netaji Subhas Institute of Technology, New Delhi
Connect on LinkedIn <http://in.linkedin.com/in/sahildua2305>
*www.sahildua.com <http://www.sahildua.com>*

**Comment by mananpal1997** [comment]
@sahildua2305  Yes,I'm. Not much. I think I can do it....

**Comment by sahildua2305** [comment]
Have you installed HackIDE on your local machine?

**Comment by sahildua2305** [comment]
Pushed live at http://hackide.herokuapp.com/. Works great!

Thank you @mananpal1997. Good work! Make sure you test the changes on the live version as well.
