### ISSUE TITLE
Server couldn't complete request.

### ISSUE THREAD

**Issue by jainaka** [sahildua2305/hackIDE#31]
Tried running python code on http://hackide.herokuapp.com/

def main():
    print "test"

if __name__ == "__main__":
    main()

Getting following error - Server couldn't complete request. Please try again!

No. of retries: 3
Error reproduce count: 3

**Comment by mananpal1997** [comment]
Ran test. It's something with hackerearth api. Showing error 504.

**Comment by jainaka** [comment]
Okay.
Cannot we give more descriptive response? This looks little generic. Is this returned from hackerearth?

**Comment by mananpal1997** [comment]
Yes. When I print the response, I either get empty response or this error:
{"errors": {}, "code_id": "6879d1z", "message": "OK", "run_status": {"status": "CE", "status_detail": "Correct the compilation/syntax errors."}, "compile_status": "Error code: 1200", "web_link": "https://code.hackerearth.com/6879d1z"}
I even tried checking for api version3 but there is also the same error.

**Comment by mananpal1997** [comment]
@jainaka Running fine now. API issue has been resolved. You can close the issue now

**Comment by sahildua2305** [comment]
@jainaka Thanks for reporting the issue.

@mananpal1997 I think we should make the error message more verbose explaining that it's API's fault and it's temporary. Can you make this change?

**Comment by mananpal1997** [comment]
@sahildua2305 sure

**Comment by ankitjain28may** [comment]
I am getting the same issue 
{"run_status":{"status":"CE","status_detail":"Correct the compilation\/syntax errors."},"compile_status":"Error code: 1200","web_link":"https:\/\/code.hackerearth.com\/633a3fj","code_id":"633a3fj"}

**Comment by aditya999123** [comment]
The API returns error 500
when input is large around 5 MB

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at api.hackerearth.com Port 80</address>
</body></html>

**Comment by iamsudip** [comment]
@sahildua2305 If you can migrate to async version of the version 3 code API, then we can assure you the uptime of code evaluation. We do not maintain version 2 API and synchronous version of version 3 API.
