### ISSUE TITLE
Can't run locally properly

### ISSUE THREAD

**Issue by mananpal1997** [sahildua2305/hackIDE#34]
At first, I would always get **ArgumentError : Client secret missing** even after running with HACKIDE_DEBUG=true.

What's more strange that I just noticed :
I changed the urls in **views.py** from **https://api.hackerearth.com/v3/code/compile/** to **https://api.hackerearth.com/code/compile/** (running with Version2)
If I hit compile now, I get the same **ArgumentError**, but when I hit run, this happened.
![one](https://cloud.githubusercontent.com/assets/13151812/17150582/a0e3042c-538d-11e6-8a68-cd236c88239a.png)
![two](https://cloud.githubusercontent.com/assets/13151812/17150583/a0f27d80-538d-11e6-9739-64c979a1612e.png)

**Comment by sahil865gupta** [comment]
If HACKIDE_DEBUG=true, then CLIENT_SECRET=''". Thats why api is creating this error. So for running on debug mode too, CLIENT_SECRET must be assigned the client secret key on HACKIDE_DEBUG=true too.

**Comment by sahildua2305** [comment]
@sahil865gupta is right! Thanks.

@mananpal1997 I thought you were already using the CLIENT_SECRET. Weren't you?

**Comment by mananpal1997** [comment]
@sahildua2305 Yes, I was.
Something strange: I reinstalled Ubuntu and now its running fine :D
