### ISSUE TITLE
Master is not live on hackide.herokuapp.com

### ISSUE THREAD

**Issue by prankymat** [sahildua2305/hackIDE#4]
Just noticed that the latest commits on master are not showing up on the main site of hackIDE. http://hackide.herokuapp.com

**Comment by sahildua2305** [comment]
Yes. I was unable to push changes to heroku in time. Internet on my machine
is down for now. I'll try pushing it in a day's time.

Sahil
http://sahildua.com

**Comment by prankymat** [comment]
:+1: will you consider linking master to herokuapp in some ways such that changes will be automatic in future?

**Comment by sahildua2305** [comment]
I will look for ways to do that. Let me know if you find a way.
Also in some cases it's better to keep the two streams different. Just like I have to avoid pushing client secret here.

**Comment by prankymat** [comment]
@sahildua2305 turns out there is a way to manage private API secrets within Heroku:
https://devcenter.heroku.com/articles/config-vars

It should be fairly straight-forward to use.
``` python
os.environ['CUSTOM_API_KEY']
```

This way the repo does not need to expose the private keys and will be safe to auto deploy to Heroku.

Hope this is useful! Look forward to the future!

**Comment by sahildua2305** [comment]
Thanks @prankymat. I have made the change. Updated the stream on the site hackIDE.
Please check once that all of the changes are reflecting there. Also it will be in sync with the master branch from now on. :)

**Comment by prankymat** [comment]
Yes! Changes are now live! :+1: for auto deploying the repo to Heroku. Closing this issue now.
