### ISSUE TITLE
Java files don't match with public class

### ISSUE THREAD

**Issue by jarroyo3** [sahildua2305/hackIDE#47]
Hello, I'm new on open source.

Do you think that is good idea save Java files make it matched with the public class name?

**Comment by sahildua2305** [comment]
Hi @jarroyo3, thanks for opening the issue!

I'm not a Java person myself. What do you think is the problem and how would you like to solve it?

**Comment by jarroyo3** [comment]
Hi!

As far as I know about Java, when the code includes something like "public class Something", the file must be named like the class name. In this case, the file must be named Something.java. 

.java file can only have one public class and it should be named as same as the .java file.

When I download a java program from hackIDE, the file is named code.java

I thought that could be a good idea (or maybe not :)) download java files taking account the public class name.

I have wrote some of code into custom.js. If you prefer I'll can share it with you and if you consider it appropriate you can merge it.

**Comment by sahildua2305** [comment]
Definitely, feel free to create a pull request with your changes. 👍

**Comment by sahildua2305** [comment]
Fixed via #48
