### ISSUE TITLE
Create a download dialog box for naming file download.

### ISSUE THREAD

**Issue by KylerSmith** [sahildua2305/hackIDE#51]
### Description

On click of the download button, automatically downloads as test.zip. 

### Steps to Reproduce

1. Click download.

**Expected behavior:** 
Should ask what the file should be named.

**Actual behavior:**
Downloads as test.zip.

**Reproduces how often:**
100%

### System version

macOS Sierra 10.12.5

**Comment by sahildua2305** [comment]
Thanks for opening this issue, @KylerSmith. Would you like to submit a pull request for it?

**Comment by samwincott** [comment]
I'd quite like to take this on, if that's ok?

**Comment by sahildua2305** [comment]
@samwincott thanks for showing interest in contributing. Feel free to take on. it's yours!
