### ISSUE TITLE
Exposing information in /admin

### ISSUE THREAD

**Issue by prankymat** [sahildua2305/hackIDE#6]
Error message with lots of information when accessing http://hackide.herokuapp.com/admin/.

Probably should set ```DEBUG = False``` in the Django settings file (at least on the master branch)?

**Comment by prankymat** [comment]
Similar situation when accessing http://hackide.herokuapp.com/accounts/profile/

**Comment by sahildua2305** [comment]
@prankymat Do you have the IDE running on your local machine? Can you check `DEBUG = False` thing on local? Not working for me.

**Comment by prankymat** [comment]
Same for me when I tried to set ```DEBUG = False```. I've tried to set ```ALLOWED_HOSTS = ['localhost']``` and many other variations but still no luck.

**Comment by sahildua2305** [comment]
Yeah, that's weird! Know someone who knows Django well?

**Comment by prankymat** [comment]
@sahildua2305 I believe it'd be a problem to serve static files from django when DEBUG = False
http://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail

**Comment by sahildua2305** [comment]
@prankymat That's why I am using whitenoise in the app. Still not working. Let me know if you try something else and are able to get it working in prod mode.

**Comment by prankymat** [comment]
@sahildua2305 finally figured out that we should call ```python manage.py collectstatic``` before serving the server up.

**Comment by sahildua2305** [comment]
@prankymat Looks good! So basically I need to run the `python manage.py collectstatic command` on the heroku server? Not sure about this thing.

**Comment by prankymat** [comment]
@sahildua2305 I believe so. :grin: 

http://stackoverflow.com/questions/14253978/heroku-performing-collectstatic-as-expected-on-deployment

**Comment by sahildua2305** [comment]
Tested. It works now with `DEBUG = False` but it is unable to serve ace editor js files. Checking it. Test it on your local.

**Comment by prankymat** [comment]
I believe I have it working on my side :eyes:

<img src="http://i.imgur.com/f45iWvA.png" width=300>

**Comment by sahildua2305** [comment]
Did you run `python manage.py collectstatic` and it's running even after that? @prankymat

**Comment by prankymat** [comment]
Yes @sahildua2305. After I executed the command above, I have a new directory namely ```staticfiles/```

<img src="http://i.imgur.com/69WTLoU.png">

Do you have it on your side too?

**Comment by sahildua2305** [comment]
@prankymat Yes. I get that and all other files are working except the ones which are being included from js in custom.js in line number 34 and 35. Don't you get such an error on your side?

![selection_052](https://cloud.githubusercontent.com/assets/5206277/12374587/c9d3e81a-bcc5-11e5-8a85-dd9155dda2f6.png)

**Comment by prankymat** [comment]
@sahildua2305 Doesn't seemed to be a problem to me.

Perhaps try clearing your browser's cache?

![screenshot from 2016-01-17 10 55 33](https://cloud.githubusercontent.com/assets/2998111/12379153/dadca078-bd08-11e5-9a93-2d411c080775.png)

**Comment by prankymat** [comment]
I found that ```ace.config.set("basePath", "/static/");``` can set the base path for AceEditor to find its file. Any ideas how to get the path from whitenoise though?

**Comment by prankymat** [comment]
Found that the path in ```custom.js``` can be ```/static/hackIDE/ace-builds/src/theme-twlight.js``` (i.e. without the version number).

Will make a pull request to reflect changes made.

**Comment by sahildua2305** [comment]
Thanks for your awesome contributions @prankymat. I have deployed the hackIDE with `debug=False` now. Please confirm once that everything is working so that I can close this issue :D

**Comment by prankymat** [comment]
@sahildua2305 everything looks fine on my side! Glad to see the changes deployed to the live site. Cheers! Closing this issue now.

**Comment by sahildua2305** [comment]
Awesome! @prankymat
