### ISSUE TITLE
Heroku page down / not working?

### ISSUE THREAD

**Issue by ghost** [sahildua2305/hackIDE#99]
The Heroku page just says " There's nothing here, yet. "

**Comment by ghost** [comment]
It seems this project is dead.

**Comment by sahildua2305** [comment]
Hi Jack, I haven't put in the effort to maintain the hosting for this project. If there's a good use-case, I'd certainly be up for hosting it again.

Could you please describe your use case? Are you looking for online code editor for one-off usage?

**Comment by ghost** [comment]
Was just looking to check it out. I’ll figure out how to host it on my Mac. Thanks though.
